### ISSUE TITLE
ops

### ISSUE THREAD

**Issue by jerko1979** [PetarTomasevic/CandidateTestGit#1]
Instalirao sam SDK kao što je navedeno u readme.txt, nemogu pokrenuti runtime .
Takodjer kada pokušam napraviti database-update dobijem "build error".
https://github.com/dotnet/core/issues/1675

**Comment by PetarTomasevic** [comment]
jesi li provjerio da je sdk 2.1.300?
Install the new version of the SDK? https://www.microsoft.com/net/download/ .NET Core 2.1 SDK v2.1.300

**Comment by jerko1979** [comment]
Riješeno. Trebao sam napraviti update VS 2017 . Sinoć sam riješio 1 zadatak. Probati ću ovih dana ovaj drugi.

**Comment by PetarTomasevic** [comment]
Odlično :)
Ja sam na godišnjem ovaj tjedan tako da samo polako, imaš vremena
