### ISSUE TITLE
What are pricing strategies?

### ISSUE THREAD

**Issue by zoran123456** [PetarTomasevic/CandidateTestGit#2]
Hi,

So what are pricing strategies? I have implemented all 5 tasks. Only missing those pricing strategies as I don't know what are they.

I will today do a code cleanup, add some comments, and send you project.

**Comment by PetarTomasevic** [comment]
Hi, you can skip this one if you implemented the rest.

**Comment by PetarTomasevic** [comment]
I'm on vacation this week so i will check everything on monday.
